<a href="https://colab.research.google.com/github/Akhilesh1118/Data-Science_NF/blob/main/Module%202/Homework/Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('/content/drive/MyDrive/Messy_Employment_India_Dataset.csv')

1. Data Inspection

In [28]:
df.head() # Shows first five rows of data frame.

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [29]:
df.info() # Display dataframe info and data types.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [ ]:
df.describe() # Shows summary statistics of numberic columns

       Years of Experience  Monthly Salary (INR)
count           980.000000           1613.000000
mean             15.244898          76886.360818
std               9.103941          41628.008054
min               0.000000           5100.000000
25%               7.000000          40700.000000
50%              16.000000          77200.000000
75%              23.000000         112400.000000
max              30.000000         149900.000000

2. Handling Missing Value.

In [ ]:
df.isnull().sum() # Counts all the values per column

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [ ]:
# Fill numeric columns with median
for col in df.select_dtypes(include="number"):
    df[col] = df[col].fillna(df[col].median())

# Fill text columns with mode
for col in df.select_dtypes(include="object"):
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years of Experience     0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

### 3. Data Cleaning and Preparation