<a href="https://colab.research.google.com/github/Akhilesh1118/Data-Science_NF/blob/main/Module%202/Classwork/Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2
#### CHAPTER 2 MERGE IN PNADAS DF.

- Merge() Funciton
- pd.merge(df1, df2, on="column_name", how="inner" )

In [ ]:
import pandas as pd

Df1 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": ["A", "B", "C", "D"]
})

Df2 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "D": ["a", "b", "c", "d"]
})

In [ ]:
pd.merge(Df1, Df2)

   A  B  D
0  1  A  a
1  2  B  b
2  3  C  c
3  4  D  d

In [ ]:
import pandas as pd

Df1 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": ["A", "B", "C", "D"]
})

Df2 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": ["a", "b", "c", "d"]
})

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="inner")

   A B_x B_y
0  1   A   a
1  2   B   b
2  3   C   c
3  4   D   d

In [ ]:

pd.merge(Df1, Df2, on = "A" , how="outer")

   A B_x B_y
0  1   A   a
1  2   B   b
2  3   C   c
3  4   D   d

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="left")

   A B_x B_y
0  1   A   a
1  2   B   b
2  3   C   c
3  4   D   d

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="right")

   A B_x B_y
0  1   A   a
1  2   B   b
2  3   C   c
3  4   D   d

In [ ]:
Df1 = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": ["A", "B", "C", "D"]
})

Df2 = pd.DataFrame({
    "A": [1, 5, 7, 3],
    "B": ["a", "b", "c", "d"]
})

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="inner")

   A B_x B_y
0  1   A   a
1  3   C   d

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="outer")

   A  B_x  B_y
0  1    A    a
1  2    B  NaN
2  3    C    d
3  4    D  NaN
4  5  NaN    b
5  7  NaN    c

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="left")

   A B_x  B_y
0  1   A    a
1  2   B  NaN
2  3   C    d
3  4   D  NaN

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="right")

   A  B_x B_y
0  1    A   a
1  5  NaN   b
2  7  NaN   c
3  3    C   d

In [ ]:
Df1 = pd.DataFrame({
    "A": [1, 2, 3, 4,5],
    "B": ["A", "B", "C", "D", "E"]
})

Df2 = pd.DataFrame({
    "A": [1, 2, 3, 4,5],
    "B": ["a", "b", "c", "d","e"]
})

In [ ]:
pd.merge(Df1, Df2, left_index = True, right_index= True)

   A_x B_x  A_y B_y
0    1   A    1   a
1    2   B    2   b
2    3   C    3   c
3    4   D    4   d
4    5   E    5   e

In [ ]:
pd.merge(Df1, Df2, left_index = True, right_index= True , suffixes=("_2019", "_2020"))

   A_2019 B_2019  A_2020 B_2020
0       1      A       1      a
1       2      B       2      b
2       3      C       3      c
3       4      D       4      d
4       5      E       5      e

In [ ]:
pd.merge(Df1, Df2, on = "A" , how="inner", indicator=True)

   A B_x B_y _merge
0  1   A   a   both
1  2   B   b   both
2  3   C   c   both
3  4   D   d   both
4  5   E   e   both